<?php

if (! $data->weixin instanceof \Weixin\Entity\Weixin) {
    throw new \Admin\Exception\RuntimeException('Invalid weixin object');
}

$this->adminPageTitleBar('公众号客户端管理', $data->weixin->getWxName());
$this->adminSideTreeMenu()->setActiveID($data->activeID);

?>

<div class="row">
    <div class="col-lg-12">
        <p>
            <a class="btn btn-default" href="<?php echo $this->url('admin/weixin-client', ['action'=>'add', 'key' => $data->weixin->getWxID()]); ?>"><i class="fa fa-plus fa-fw"></i> 添加客户端</a>
        </p>
        <table class="table table-hover">
            <tr>
                <th>客户端名称</th>
                <th>客户端 IP 限制</th>
                <th>客户端域名限制</th>
                <th>客户端生效时间</th>
                <th>客户端失效时间</th>
                <th>客户端 API 清单</th>
                <th>客户端操作</th>
            </tr>
            <?php
            $clients = $data->weixin->getWxClients();
            foreach ($clients as $client) {
                ?>
                <tr>
                    <td height="50"><?php echo $client->getClientName(); ?></td>
                    <td><?php echo '*' == $client->getClientIp() ? '不限制' : $client->getClientIp(); ?></td>
                    <td><?php echo '*' == $client->getClientDomain() ? '不限制' : $client->getClientDomain(); ?></td>
                    <td><?php echo $client->getClientStart()->format('Y-m-d'); ?></td>
                    <td><?php echo $client->getClientExpired()->format('Y-m-d'); ?></td>
                    <td>
                        <ul class="nav nav-pills actions-list" role="tablist">
                            <li role="presentation" class="dropdown">
                                <?php if (empty($client->getClientApi())) { ?>
                                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                                        无授权 API
                                    </a>
                                <?php } else { ?>
                                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                                        已授权 API <span class="caret"></span>
                                    </a>
                                    <ul class="dropdown-menu" role="menu">
                                        <?php
                                        $api = json_decode($client->getClientApi());
                                        $i = 0;
                                        foreach ($data->apiList as $k => $v) {
                                            if (in_array($k, $api)) {
                                                $i++;
                                        ?>
                                        <?php if(1 != $i) { ?><li class="divider"></li><?php } ?>
                                        <li>
                                            <a href="#">
                                                <i class="fa fa-link fa-fw" aria-hidden="true"></i> <?php echo $v; ?>
                                            </a>
                                        </li>
                                        <?php } } ?>
                                    </ul>
                                <?php } ?>
                            </li>
                        </ul>
                    </td>
                    <td>
                        <ul class="nav nav-pills actions-list" role="tablist">
                            <li role="presentation" class="dropdown">
                                <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                                    选择操作 <span class="caret"></span>
                                </a>
                                <ul class="dropdown-menu" role="menu">
                                    <li>
                                        <a href="<?php echo $this->url('admin/weixin-client', ['action' => 'edit', 'key' => $client->getClientID()]); ?>">
                                            <i class="fa fa-edit fa-fw" aria-hidden="true"></i> 修改配置
                                        </a>
                                    </li>
                                    <li class="divider"></li>
                                    <li>
                                        <a href="<?php echo $this->url('admin/weixin-client', ['action' => 'document', 'key' => $client->getClientID()]); ?>" target="_blank">
                                            <i class="fa fa-file-excel-o fa-fw" aria-hidden="true"></i> 下载 API 文档
                                        </a>
                                    </li>
                                    <li class="divider"></li>
                                    <li>
                                        <a href="<?php echo $this->url('admin/weixin-client', ['action' => 'delete', 'key' => $client->getClientID()]); ?>">
                                            <i class="fa fa-trash fa-fw" aria-hidden="true"></i> 删除客户端
                                        </a>
                                    </li>
                                </ul>
                            </li>
                        </ul>
                    </td>
                </tr>

                <?php
            }
            ?>
        </table>
    </div>
</div>

