<?php echo $this->doctype(); ?>

<html lang="en">
<head>
    <meta charset="utf-8">
    <?php echo $this->headTitle('管理中心')->setSeparator(' - ')->setAutoEscape(false); ?>

    <?php echo $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge');
    ?>

    <?php if('development' == @$env) { ?>
        <meta http-equiv="pragma" content="no-cache">
        <meta http-equiv="cache-control" content="no-cache">
        <meta http-equiv="expires" content="0">
    <?php } ?>


    <!-- Le styles -->
    <?php echo $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/favicon.ico'])
        ->prependStylesheet($this->basePath('css/admin/style.css'))
        ->prependStylesheet($this->basePath('open-source-assets/font-awesome-4.7.0/css/font-awesome.min.css'))
        ->prependStylesheet($this->basePath('open-source-assets/bootstrap-3.3.7-dist/css/bootstrap.min.css'));
    ?>
</head>

<body>

<?php echo $this->content; ?>


<!-- Scripts -->
<?php
$this->inlineScript()->captureStart();
echo <<<JS
function globalFuncMoveToCentered()
{
    var ww = $(window).width();
    var wh = $(window).height();

    var dw = $("#centered_container").width();
    var dh = $("#centered_container").height();

    var left = 0;
    var top  = 0;
    if(ww > dw) {
        left = (ww - dw) / 2;
    }
    if(wh > dh) {
        top = ((wh - dh) / 2) * 0.8;
    }

    $("#centered_container").css({"left": left, "top": top});

}

$(function(){
    globalFuncMoveToCentered();
    $(window).resize(function(){
        globalFuncMoveToCentered();
    });
});
$(function(){
    $("form").submit(function () { // forbid re-submit
        $(":submit", this).attr("disabled","disabled");
    });
});
JS;
$this->inlineScript()->captureEnd();
?>

<?php echo $this->headScript()
    ->prependFile($this->basePath('open-source-assets/bootstrap-3.3.7-dist/js/bootstrap.min.js'))
    ->prependFile($this->basePath('open-source-assets/jquery-3.1.1/jquery-3.1.1.min.js'));
?>

<?php echo $this->inlineScript(); ?>

</body>
</html>
