<?php

use Admin\Form\WeixinEventForm as Form;

if (! $data->weixin instanceof \Weixin\Entity\Weixin) {
    throw new \Admin\Exception\RuntimeException('Invalid weixin object');
}

$this->adminPageTitleBar('公众号事件添加', $data->weixin->getWxName());
$this->adminSideTreeMenu()->setActiveID($data->activeID);

$input = $data->form->get(Form::FIELD_TYPE);
$input->setAttributes([
    'class' => 'form-control'
]);

$input = $data->form->get(Form::FIELD_TARGET);
$input->setAttributes([
    'class' => 'form-control',
    'placeholder' => 'Default'
]);
$this->formLocalMessage($input, [
    \Zend\Validator\NotEmpty::IS_EMPTY => '事件对象不能为空',
    \Zend\Validator\StringLength::TOO_SHORT => '事件对象名太短!',
    \Zend\Validator\StringLength::TOO_LONG => '事件对象名太长!',
]);

$input = $data->form->get(Form::FIELD_HANDLE);
$input->setAttributes([
    'class' => 'form-control'
]);

$input = $data->form->get(Form::FIELD_RESULT);
$input->setAttributes([
    'class' => 'form-control',
]);

$data->form->get(Form::FIELD_SUBMIT)->setAttributes(['class'=>'btn btn-primary']);

$data->form->prepare();

?>


<div class="row">
    <div class="col-lg-6">

        <?php echo $this->form()->openTag($data->form); ?>

        <div class="form-group">
            <?php echo $this->formElement($data->form->get(Form::FIELD_CSRF)); ?>
        </div>

        <div class="form-group">
            <?php echo $this->formLabel($data->form->get(Form::FIELD_TYPE), '选择事件类型'); ?>
            <?php echo $this->formElement($data->form->get(Form::FIELD_TYPE)); ?>
            <?php echo $this->formElementErrors($data->form->get(Form::FIELD_TYPE)); ?>
        </div>

        <div class="form-group">
            <?php echo $this->formLabel($data->form->get(Form::FIELD_TARGET), '设置事件对象'); ?>
            <?php echo $this->formElement($data->form->get(Form::FIELD_TARGET)); ?>
            <p class="text-muted">
                <small>默认事件对象请设置为: Default</small>
            </p>
            <?php echo $this->formElementErrors($data->form->get(Form::FIELD_TARGET)); ?>
        </div>

        <div class="form-group">
            <?php echo $this->formLabel($data->form->get(Form::FIELD_HANDLE), '选择事件回应方式'); ?>
            <?php echo $this->formElement($data->form->get(Form::FIELD_HANDLE)); ?>
            <p class="text-muted">
                <small>使用接口回应消息务必在5秒内返回结果. 否则失败!</small>
            </p>
            <?php echo $this->formElementErrors($data->form->get(Form::FIELD_HANDLE)); ?>
        </div>

        <div class="form-group">
            <?php echo $this->formLabel($data->form->get(Form::FIELD_RESULT), '事件回应设置'); ?>
            <?php echo $this->formElement($data->form->get(Form::FIELD_RESULT)); ?>
            <p class="text-muted">
                <small>填入转发的 API 地址或者回应的消息模板. 模板内容请参考微信公众平台文档</small>
            </p>
            <?php echo $this->formElementErrors($data->form->get(Form::FIELD_RESULT)); ?>
        </div>

        <div class="form-group">
            <?php echo $this->formElement($data->form->get(Form::FIELD_SUBMIT)); ?>
        </div>

        <?php echo $this->form()->closeTag(); ?>

    </div>
</div>

