<?php

if (! $data->weixin instanceof \Weixin\Entity\Weixin) {
    throw new \Admin\Exception\RuntimeException('Invalid weixin object');
}

$this->adminPageTitleBar('公众号事件管理', $data->weixin->getWxName());
$this->adminSideTreeMenu()->setActiveID($data->activeID);

?>

<div class="row">
    <div class="col-lg-12">
        <p>
            <a class="btn btn-default"
               href="<?php echo $this->url('admin/weixin-event', ['action'=>'add', 'key' => $data->weixin->getWxID()]); ?>">
                <i class="fa fa-plus fa-fw"></i> 添加监听事件</a>
            <span> &nbsp;&nbsp; </span>
        </p>

        <table class="table table-hover">
            <tr>
                <th>事件类型</th>
                <th>事件目标</th>
                <th>回应设置</th>
                <th>操作</th>
            </tr>
        </table>

    </div>
</div>

