<?php
use Admin\Form\UpdatePasswordForm;

$this->adminPageTitleBar('更新密码');


$data->form->get(UpdatePasswordForm::FIELD_OLD_PASSWORD)->setAttributes([
    'class' => 'form-control',
    'placeholder' => '请输入现在的密码',
]);

$data->form->get(UpdatePasswordForm::FIELD_NEW_PASSWORD)->setAttributes([
    'class' => 'form-control',
    'placeholder' => '设置一个新密码',
]);

$data->form->get(UpdatePasswordForm::FIELD_RE_NEW_PASSWORD)->setAttributes([
    'class' => 'form-control',
    'placeholder' => '再输入一次新密码',
]);

$data->form->get(UpdatePasswordForm::FIELD_SUBMIT)->setAttributes(['class'=>'btn btn-primary', 'value' => '更新密码']);

$data->form->prepare();

?>


<div class="row">
    <div class="col-md-6">

        <p>密码修改完成后, 请牢记新密码, 在下次登录将启用新密码登入.</p>

        <?php echo $this->form()->openTag($data->form); ?>

        <div class="form-group">
            <?php echo $this->formElement($data->form->get(UpdatePasswordForm::FIELD_CSRF)); ?>
        </div>

        <div class="form-group">
            <?php echo $this->formLabel($data->form->get(UpdatePasswordForm::FIELD_OLD_PASSWORD), '当前密码'); ?>
            <?php echo $this->formElement($data->form->get(UpdatePasswordForm::FIELD_OLD_PASSWORD)); ?>
            <?php echo $this->formElementErrors($data->form->get(UpdatePasswordForm::FIELD_OLD_PASSWORD)); ?>
        </div>

        <div class="form-group">
            <?php echo $this->formLabel($data->form->get(UpdatePasswordForm::FIELD_NEW_PASSWORD), '新密码'); ?>
            <?php echo $this->formElement($data->form->get(UpdatePasswordForm::FIELD_NEW_PASSWORD)); ?>
            <?php echo $this->formElementErrors($data->form->get(UpdatePasswordForm::FIELD_NEW_PASSWORD)); ?>
        </div>

        <div class="form-group">
            <?php echo $this->formLabel($data->form->get(UpdatePasswordForm::FIELD_RE_NEW_PASSWORD), '确认新密码'); ?>
            <?php echo $this->formElement($data->form->get(UpdatePasswordForm::FIELD_RE_NEW_PASSWORD)); ?>
            <?php echo $this->formElementErrors($data->form->get(UpdatePasswordForm::FIELD_RE_NEW_PASSWORD)); ?>
        </div>

        <div class="form-group">
            <?php echo $this->formElement($data->form->get(UpdatePasswordForm::FIELD_SUBMIT)); ?>
        </div>

        <?php echo $this->form()->closeTag(); ?>

    </div>
</div>

