<?php
use Admin\Form\UpdateProfileForm;

$this->adminPageTitleBar('更新我的资料');


$data->form->get(UpdateProfileForm::FIELD_NAME)->setAttributes([
    'class' => 'form-control',
    'placeholder' => $data->adminer->getAdminName(),
]);

$data->form->get(UpdateProfileForm::FIELD_SUBMIT)->setAttributes(['class'=>'btn btn-primary']);

$data->form->prepare();

?>

<div class="row">
    <div class="col-lg-6">

        <?php echo $this->form()->openTag($data->form); ?>

        <div class="form-group">
            <?php echo $this->formElement($data->form->get(UpdateProfileForm::FIELD_CSRF)); ?>

        </div>

        <div class="form-group">
            <?php echo $this->formLabel($data->form->get(UpdateProfileForm::FIELD_NAME), '更新名字'); ?>
            <?php echo $this->formElement($data->form->get(UpdateProfileForm::FIELD_NAME)); ?>
            <?php echo $this->formElementErrors($data->form->get(UpdateProfileForm::FIELD_NAME)); ?>

        </div>

        <div class="form-group">
            <?php echo $this->formElement($data->form->get(UpdateProfileForm::FIELD_SUBMIT)); ?>

        </div>

        <?php echo $this->form()->closeTag(); ?>

    </div>
</div>

