<?php

use Admin\Form\WeixinTagForm as Form;

if (! $data->weixin instanceof \Weixin\Entity\Weixin) {
    throw new \Admin\Exception\RuntimeException('Invalid weixin object');
}

$this->adminPageTitleBar('添加公众号标签', $data->weixin->getWxName());
$this->adminSideTreeMenu()->setActiveID($data->activeID);

$input = $data->form->get(Form::FIELD_NAME);
$input->setAttributes([
    'class' => 'form-control',
    'placeholder' => '标签名称'
]);
$this->formLocalMessage($input, [
    \Zend\Validator\NotEmpty::IS_EMPTY => '会员标签不能为空',
    \Zend\Validator\StringLength::TOO_SHORT => '标签名太短!',
    \Zend\Validator\StringLength::TOO_LONG => '标签名太长!',
]);

$data->form->get(Form::FIELD_SUBMIT)->setAttributes(['class'=>'btn btn-primary']);

$data->form->prepare();

?>

<div class="row">
    <div class="col-lg-6">

        <?php echo $this->form()->openTag($data->form); ?>

        <div class="form-group">
            <?php echo $this->formElement($data->form->get(Form::FIELD_CSRF)); ?>
        </div>

        <div class="form-group">
            <?php echo $this->formLabel($data->form->get(Form::FIELD_NAME), '设置标签名称'); ?>
            <?php echo $this->formElement($data->form->get(Form::FIELD_NAME)); ?>
            <?php echo $this->formElementErrors($data->form->get(Form::FIELD_NAME)); ?>
        </div>

        <div class="form-group">
            <?php echo $this->formElement($data->form->get(Form::FIELD_SUBMIT)); ?>
        </div>

        <?php echo $this->form()->closeTag(); ?>

    </div>
</div>
