<?php

use Admin\Form\AdminerForm;

$this->adminPageTitleBar('创建新成员');
$this->adminSideTreeMenu()->setActiveID($data->activeID);

$data->form->get(AdminerForm::FIELD_EMAIL)->setAttributes([
    'class' => 'form-control',
    'placeholder' => '成员登入账号(E-mail)'
]);

$data->form->get(AdminerForm::FIELD_PASSWORD)->setAttributes([
    'class' => 'form-control',
]);

$data->form->get(AdminerForm::FIELD_NAME)->setAttributes([
    'class' => 'form-control',
    'placeholder' => '成员名称'
]);

$data->form->get(AdminerForm::FIELD_EXPIRED)->setAttributes([
    'class' => 'form-control',
    'value' => date('Y-m-d', strtotime("+1 year")),
]);

$data->form->get('submit')->setAttributes(['class'=>'btn btn-primary']);

$data->form->prepare();

?>


<div class="row">
    <div class="col-lg-6">

        <?php echo $this->form()->openTag($data->form); ?>

        <div class="form-group">
            <?php echo $this->formElement($data->form->get(AdminerForm::FIELD_CSRF)); ?>

        </div>

        <div class="form-group">
            <?php echo $this->formLabel($data->form->get(AdminerForm::FIELD_EMAIL), '设定登入账号(E-mail)'); ?>
            <?php echo $this->formElement($data->form->get(AdminerForm::FIELD_EMAIL)); ?>
            <?php echo $this->formElementErrors($data->form->get(AdminerForm::FIELD_EMAIL)); ?>

        </div>

        <div class="form-group">
            <?php echo $this->formLabel($data->form->get(AdminerForm::FIELD_PASSWORD), '设定登入密码'); ?>
            <?php echo $this->formElement($data->form->get(AdminerForm::FIELD_PASSWORD)); ?>
            <?php echo $this->formElementErrors($data->form->get(AdminerForm::FIELD_PASSWORD)); ?>

        </div>

        <div class="form-group">
            <?php echo $this->formLabel($data->form->get(AdminerForm::FIELD_NAME), '成员名字'); ?>
            <?php echo $this->formElement($data->form->get(AdminerForm::FIELD_NAME)); ?>
            <?php echo $this->formElementErrors($data->form->get(AdminerForm::FIELD_NAME)); ?>

        </div>

        <div class="form-group">
            <?php echo $this->formLabel($data->form->get(AdminerForm::FIELD_EXPIRED), '过期时间'); ?>
            <?php echo $this->formElement($data->form->get(AdminerForm::FIELD_EXPIRED)); ?>
            <?php echo $this->formElementErrors($data->form->get(AdminerForm::FIELD_EXPIRED)); ?>

        </div>

        <div class="form-group">
            <?php echo $this->formElement($data->form->get(AdminerForm::FIELD_SUBMIT)); ?>

        </div>

        <?php echo $this->form()->closeTag(); ?>


    </div>
</div>
