<?php
use Admin\Form\AdminerForm;

$this->adminPageTitleBar('设置过期时间');
$this->adminSideTreeMenu()->setActiveID($data->activeID);


$data->form->get(AdminerForm::FIELD_EXPIRED)->setAttributes([
    'class' => 'form-control',
    'value' => $data->adminer->getAdminExpired()->format('Y-m-d'),
]);

$data->form->get(AdminerForm::FIELD_SUBMIT)->setAttributes(['class'=>'btn btn-primary']);

$data->form->prepare();

?>


<div class="row">
    <div class="col-lg-6">

        <?php echo $this->form()->openTag($data->form); ?>

        <div class="form-group">
            <?php echo $this->formElement($data->form->get(AdminerForm::FIELD_CSRF)); ?>
        </div>

        <div class="form-group">
            <?php echo $this->formLabel($data->form->get(AdminerForm::FIELD_EXPIRED), '设定账号过期时间'); ?>
            <?php echo $this->formElement($data->form->get(AdminerForm::FIELD_EXPIRED)); ?>
            <?php echo $this->formElementErrors($data->form->get(AdminerForm::FIELD_EXPIRED)); ?>
        </div>

        <div class="form-group">
            <?php echo $this->formElement($data->form->get(AdminerForm::FIELD_SUBMIT)); ?>
        </div>

        <?php echo $this->form()->closeTag(); ?>

    </div>
</div>
