<?php
use Admin\Form\AdminerForm;

$this->adminPageTitleBar('成员等级更新');
$this->adminSideTreeMenu()->setActiveID($data->activeID);


$data->form->get(AdminerForm::FIELD_LEVEL)->setAttributes([
    'class' => 'form-control',
    'value' => $data->adminer->getAdminLevel(),
]);

$data->form->get(AdminerForm::FIELD_SUBMIT)->setAttributes(['class'=>'btn btn-primary']);

$data->form->prepare();

?>


<div class="row">
    <div class="col-lg-6">

        <?php echo $this->form()->openTag($data->form); ?>

        <div class="form-group">
            <?php echo $this->formElement($data->form->get(AdminerForm::FIELD_CSRF)); ?>
        </div>

        <div class="form-group">
            <?php echo $this->formLabel($data->form->get(AdminerForm::FIELD_LEVEL), '帐号等级'); ?>
            <?php echo $this->formElement($data->form->get(AdminerForm::FIELD_LEVEL)); ?>
            <?php echo $this->formElementErrors($data->form->get(AdminerForm::FIELD_LEVEL)); ?>
        </div>

        <div class="form-group">
            <?php echo $this->formElement($data->form->get(AdminerForm::FIELD_SUBMIT)); ?>
        </div>

        <?php echo $this->form()->closeTag(); ?>

    </div>
</div>
