<?php
use Admin\Form\AdminerForm;

$this->adminPageTitleBar('更新密码');
$this->adminSideTreeMenu()->setActiveID($data->activeID);

$data->form->get(AdminerForm::FIELD_PASSWORD)->setAttributes([
    'class' => 'form-control',
])->setOptions([
    'label' => '设置新密码',
]);

$data->form->get(AdminerForm::FIELD_SUBMIT)->setAttributes(['class'=>'btn btn-primary']);

$data->form->prepare();

?>


<div class="row">
    <div class="col-lg-6">

        <?php echo $this->form()->openTag($data->form); ?>

        <div class="form-group">
            <?php echo $this->formElement($data->form->get(AdminerForm::FIELD_CSRF)); ?>
        </div>

        <div class="form-group">
            <?php echo $this->formLabel($data->form->get(AdminerForm::FIELD_PASSWORD), '帐号密码'); ?>
            <?php echo $this->formElement($data->form->get(AdminerForm::FIELD_PASSWORD)); ?>
            <?php echo $this->formElementErrors($data->form->get(AdminerForm::FIELD_PASSWORD)); ?>
        </div>

        <div class="form-group">
            <?php echo $this->formElement($data->form->get(AdminerForm::FIELD_SUBMIT)); ?>
        </div>

        <?php echo $this->form()->closeTag(); ?>

    </div>
</div>
