<?php
use Admin\Form\AdminerForm;

$this->adminPageTitleBar('修改成员信息');
$this->adminSideTreeMenu()->setActiveID($data->activeID);

$data->form->get(AdminerForm::FIELD_EMAIL)->setAttributes([
    'class' => 'form-control',
    'value' => $data->adminer->getAdminEmail(),
    'placeholder' => 'Enter the email'
]);

$data->form->get(AdminerForm::FIELD_NAME)->setAttributes([
    'class' => 'form-control',
    'value' => $data->adminer->getAdminName(),
    'placeholder' => 'Enter the name'
]);

$data->form->get(AdminerForm::FIELD_SUBMIT)->setAttributes(['class'=>'btn btn-primary']);

$data->form->prepare();

?>


<div class="row">
    <div class="col-lg-6">

        <?php echo $this->form()->openTag($data->form); ?>

        <div class="form-group">
            <?php echo $this->formElement($data->form->get(AdminerForm::FIELD_CSRF)); ?>
        </div>

        <div class="form-group">
            <?php echo $this->formLabel($data->form->get(AdminerForm::FIELD_EMAIL), '帐号 E-mail 地址'); ?>
            <?php echo $this->formElement($data->form->get(AdminerForm::FIELD_EMAIL)); ?>
            <?php echo $this->formElementErrors($data->form->get(AdminerForm::FIELD_EMAIL)); ?>
        </div>

        <div class="form-group">
            <?php echo $this->formLabel($data->form->get(AdminerForm::FIELD_NAME), '帐号名称'); ?>
            <?php echo $this->formElement($data->form->get(AdminerForm::FIELD_NAME)); ?>
            <?php echo $this->formElementErrors($data->form->get(AdminerForm::FIELD_NAME)); ?>
        </div>

        <div class="form-group">
            <?php echo $this->formElement($data->form->get(AdminerForm::FIELD_SUBMIT)); ?>
        </div>

        <?php echo $this->form()->closeTag(); ?>

    </div>
</div>
