<?php
use Admin\Form\WeixinForm;

if (! $data->weixin instanceof \Weixin\Entity\Weixin) {
    throw new \Admin\Exception\RuntimeException('Invalid weixin object');
}

$this->adminPageTitleBar('添加公众号', $data->weixin->getWxName());
$this->adminSideTreeMenu()->setActiveID($data->activeID);

$input = $data->form->get(WeixinForm::FIELD_APPSECRET);
$input->setAttributes([
    'class' => 'form-control',
    'placeholder' => '这里请填写 AppSecret',
    'value' => $data->weixin->getWxAppSecret(),
]);
$this->formLocalMessage($input, [
    \Zend\Validator\NotEmpty::IS_EMPTY => '微信公众号的 AppSecret 不填写后面没法继续愉快的玩耍了!',
    \Zend\Validator\Regex::NOT_MATCH => '请填写正确的 AppSecret, 请注意大小写!',
]);


$input = $data->form->get(WeixinForm::FIELD_NAME);
$input->setAttributes([
    'class' => 'form-control',
    'placeholder' => '公众号名称',
    'value' => $data->weixin->getWxName(),
]);
$this->formLocalMessage($input, [
    \Zend\Validator\NotEmpty::IS_EMPTY => '请为此公众号设置一个名称.',
]);

$input = $data->form->get(WeixinForm::FIELD_TOKEN);
$input->setAttributes([
    'class' => 'form-control',
    'placeholder' => '公众号接入TOKEN',
    'value' => $data->weixin->getWxToken(),
]);
$this->formLocalMessage($input, [
    \Zend\Validator\NotEmpty::IS_EMPTY => '请填写此公众号开发者接入 Token.',
    '__undefined__' => 'Token 长度在3-32个字符内有效!',
]);

$input = $data->form->get(WeixinForm::FIELD_ENCODING_AES_KEY);
$input->setAttributes([
    'class' => 'form-control',
    'placeholder' => '公众号接入 EncodingAESKey',
    'value' => $data->weixin->getWxEncodingAESKey(),
]);
$this->formLocalMessage($input, [
    \Zend\Validator\NotEmpty::IS_EMPTY => '请填写此公众号开发者接入 EncodingAESKey.',
    '__undefined__' => 'EncodingAESKey 长度在1-43个字符内有效!',
]);

$input = $data->form->get(WeixinForm::FIELD_TRANSFER_MODE);
$input->setAttributes([
    'class' => 'form-control',
    'value' => $data->weixin->getWxTransferMode(),
]);
$this->formLocalMessage($input, [
    \Zend\Validator\NotEmpty::IS_EMPTY => '请设置好消息加密模式.',
]);


$data->form->get(WeixinForm::FIELD_SUBMIT)->setAttributes(['class'=>"btn btn-primary"]);

$data->form->prepare();

$alert = '';
if(!empty($data->error)) {
    $alert = 'alert("' . $data->error . '");';
}


$this->inlineScript()->captureStart();
echo <<<JS
$(function () {
    $("form").submit(function () {
        
        var appsecret = $("#appsecret").val();
        if(appsecret.length < 3) {
            $("#appsecret").focus();
            setTimeout(function() {
                $("#submit").attr("disabled", false);  
            }, 500);
            return false;
        }
        if(confirm("接下来进行修改后的公众号信息进行验证. 可能需要一点时间. 是否需要继续修改?")) {
            return true;
        } else {
            setTimeout(function() {
                $("#submit").attr("disabled", false);  
            }, 500);
            return false;
        }
    });
    $alert
});
JS;
$this->inlineScript()->captureEnd();

?>


<div class="row">
    <div class="col-lg-6">

        <div class="form-group alert alert-warning" role="alert">
            <strong>请注意:</strong> 提交创建的公众号会与微信平台进行验证. <br>
            公众号经过验证可用后 <strong>AppID</strong> 将不再被允许修改! <br>
            验证过程可能需要点时间, 请勿关闭本页. 验证完毕会自动刷新页面.
        </div>

        <?php echo $this->form()->openTag($data->form); ?>

        <div class="form-group">
            <?php echo $this->formElement($data->form->get(WeixinForm::FIELD_CSRF)); ?>
        </div>

        <div class="form-group">
            <label>微信公众号 AppID</label>
            <input class="form-control" type="text" value="<?php echo $data->weixin->getWxAppID(); ?>" disabled="disabled">
        </div>

        <div class="form-group">
            <?php echo $this->formLabel($data->form->get(WeixinForm::FIELD_APPSECRET), '微信公众号 AppSecret'); ?>
            <?php echo $this->formElement($data->form->get(WeixinForm::FIELD_APPSECRET)); ?>
            <?php echo $this->formElementErrors($data->form->get(WeixinForm::FIELD_APPSECRET)); ?>
        </div>

        <div class="form-group">
            <?php echo $this->formLabel($data->form->get(WeixinForm::FIELD_NAME), '微信公众号名称'); ?>
            <?php echo $this->formElement($data->form->get(WeixinForm::FIELD_NAME)); ?>
            <?php echo $this->formElementErrors($data->form->get(WeixinForm::FIELD_NAME)); ?>
        </div>

        <div class="form-group">
            <?php echo $this->formLabel($data->form->get(WeixinForm::FIELD_TOKEN), '微信公众号Token'); ?>
            <?php echo $this->formElement($data->form->get(WeixinForm::FIELD_TOKEN)); ?>
            <p class="text-muted">
                <small>必须为英文或数字，长度为3-32字符。</small>
            </p>
            <?php echo $this->formElementErrors($data->form->get(WeixinForm::FIELD_TOKEN)); ?>
        </div>

        <div class="form-group">
            <?php echo $this->formLabel($data->form->get(WeixinForm::FIELD_ENCODING_AES_KEY), '微信公众号消息加密KEY'); ?>
            <?php echo $this->formElement($data->form->get(WeixinForm::FIELD_ENCODING_AES_KEY)); ?>
            <p class="text-muted">
                <small>消息加密密钥由43位字符组成，可随机修改，字符范围为A-Z，a-z，0-9。</small>
            </p>
            <?php echo $this->formElementErrors($data->form->get(WeixinForm::FIELD_ENCODING_AES_KEY)); ?>
        </div>

        <div class="form-group">
            <?php echo $this->formLabel($data->form->get(WeixinForm::FIELD_TRANSFER_MODE), '微信公众号消息加密模式'); ?>
            <?php echo $this->formElement($data->form->get(WeixinForm::FIELD_TRANSFER_MODE)); ?>
            <?php echo $this->formElementErrors($data->form->get(WeixinForm::FIELD_TRANSFER_MODE)); ?>
        </div>


        <div class="form-group">
            <?php echo $this->formElement($data->form->get(WeixinForm::FIELD_SUBMIT)); ?>
        </div>

        <?php echo $this->form()->closeTag(); ?>

    </div>
</div>
