<?php

$this->adminPageTitleBar('公众号列表');
$this->adminSideTreeMenu()->setActiveID($data->activeID);


$this->inlineScript()->captureStart();
echo <<<JS

$(function(){
    
    $("#pageModal").on("show.bs.modal", function() {
        $(this).find(".modal-content").html('<div class="well well-lg text-center" style="margin:0;">处理中. 请稍等...</div>');
    });
    
    $("#pageModal").on("hidden.bs.modal", function() {
        $("#pageModal > div").removeClass("modal-sm");
    });
    
    
    $(".dropdown-menu .delete").click(function() {
        if(confirm("确定需要删除公众号么?")) {
            $("#pageModal > div").addClass("modal-sm");
            $('#pageModal').modal({
                show: true,
                keyboard: false,
                backdrop: "static"
            });
            
            var tr = $(this).parent().parent().parent().parent().parent().parent();
            var deleteUrl = $(this).attr("href");
            $.ajax({
                url: deleteUrl,
                async: true,
                cache: false,
                global: false,
                type: 'GET',
                dataType: 'json',
                complete: function(jqXHR, textStatus) {
                    
                },
                error: function(jqXHR, textStatus, errorThrown) {
                    alert('删除失败, 请重新再试!');
                },
                success: function(data, textStatus, jqXHR) {
                     tr.hide();
                     $('#pageModal').modal('hide');
                }
            });
            
            return false;
        } 
        return false;
    });
    
    $(".dropdown-menu .refresh").click(function() {
        if(confirm("刷新公众号 AccessToken 需要和微信服务器通信. " + String.fromCharCode(10)  + "刷新完成页面会自动刷新, 是否需要刷新?")) {
        
            $("#pageModal > div").addClass("modal-sm");
            $('#pageModal').modal({
                show: true,
                keyboard: false,
                backdrop: "static"
            });
        
            var refreshUrl = $(this).attr("href");
            $.ajax({
                url: refreshUrl,
                async: true,
                cache: false,
                global: false,
                type: 'GET',
                dataType: 'json',
                complete: function(jqXHR, textStatus) {
                    
                },
                error: function(jqXHR, textStatus, errorThrown) {
                    alert('刷新失败, 请重新再试!');
                    location.reload(true);
                },
                success: function(data, textStatus, jqXHR) {
                     $('#pageModal').modal('hide');
                }
            });
            
            
            return false;
        }
        return false;
    });
});

JS;
$this->inlineScript()->captureEnd();

?>


<div class="row">
    <div class="col-lg-12">
        <p>
            <a class="btn btn-default" href="<?php echo $this->url('admin/weixin', ['action' => 'add']); ?>">
                <i class="fa fa-plus fa-fw"></i> 添加公众号
            </a>
        </p>

        <table class="table table-striped">
            <tr>
                <th width="20%">名称(编号)</th>
                <th width="30%">AppID/AppSecret</th>
                <th>操作</th>
            </tr>
            <?php
            foreach ($data->entities as $entity) {
                if (! $entity instanceof \Weixin\Entity\Weixin) {
                    continue;
                }
            ?>
                <tr>
                    <td><?php echo $entity->getWxName(); ?> (<strong><?php echo $entity->getWxID(); ?></strong>)</td>
                    <td><?php echo $entity->getWxAppID(); ?><br /><?php echo substr($entity->getWxAppSecret(), 0, strlen($entity->getWxAppID()) - 3); ?>***</td>
                    <td>
                        <ul class="nav nav-pills actions-list" role="tablist">
                            <li role="presentation" class="dropdown">
                                <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                                    操作选项 <span class="caret"></span>
                                </a>
                                <ul class="dropdown-menu" role="menu">
                                    <li>
                                        <a class="delete" href="<?php echo $this->url('admin/weixin', ['action' => 'delete', 'key' => $entity->getWxID()]); ?>">
                                            <i class="fa fa-close fa-fw" aria-hidden="true"></i> 删除公众号
                                        </a>
                                    </li>
                                    <li class="divider"></li>
                                    <li>
                                        <a href="<?php echo $this->url('admin/weixin', ['action' => 'edit', 'key' => $entity->getWxID()]); ?>">
                                            <i class="fa fa-edit fa-fw" aria-hidden="true"></i> 修改公众号
                                        </a>
                                    </li>
                                    <li class="divider"></li>
                                    <li>
                                        <a class="refresh" href="<?php echo $this->url('admin/weixin', ['action' => 'refresh', 'key' => $entity->getWxID()]); ?>">
                                            <i class="fa fa-refresh fa-fw" aria-hidden="true"></i> 刷新Token
                                        </a>
                                    </li>
                                    <li class="divider"></li>
                                    <li>
                                        <a href="<?php echo $this->url('admin/weixin-client', ['action' => 'index', 'key' => $entity->getWxID()]); ?>">
                                            <i class="fa fa-desktop fa-fw" aria-hidden="true"></i> 客户端管理
                                        </a>
                                    </li>
                                    <li class="divider"></li>
                                    <li>
                                        <a href="<?php echo $this->url('admin/weixin-tag', ['action' => 'index', 'key' => $entity->getWxID()]); ?>">
                                            <i class="fa fa-tags fa-fw" aria-hidden="true"></i> Tag 管理
                                        </a>
                                    </li>
                                    <li class="divider"></li>
                                    <li>
                                        <a href="<?php echo $this->url('admin/weixin-menu', ['action' => 'index', 'key' => $entity->getWxID()]); ?>">
                                            <i class="fa fa-navicon fa-fw" aria-hidden="true"></i> 菜单管理
                                        </a>
                                    </li>
                                    <li class="divider"></li>
                                    <li>
                                        <a href="<?php echo $this->url('admin/weixin-qrcode', ['action' => 'index', 'key' => $entity->getWxID()]); ?>">
                                            <i class="fa fa-qrcode fa-fw" aria-hidden="true"></i> 二维码管理
                                        </a>
                                    </li>
                                    <li class="divider"></li>
                                    <li>
                                        <a href="#">
                                            <i class="fa fa-comments fa-fw" aria-hidden="true"></i> 关注欢迎语管理
                                        </a>
                                    </li>
                                </ul>
                            </li>
                        </ul>
                    </td>
                </tr>
            <?php } ?>
        </table>
    </div>
</div>


