<?php

if (! $data->weixin instanceof \Weixin\Entity\Weixin) {
    throw new \Admin\Exception\RuntimeException('Invalid weixin object');
}

$this->adminPageTitleBar('公众号菜单管理', $data->weixin->getWxName());
$this->adminSideTreeMenu()->setActiveID($data->activeID);

?>

<div class="row">
    <div class="col-lg-12">
        <p>
            <a class="btn btn-default"
                href="<?php echo $this->url('admin/weixin-menu', ['action'=>'add', 'key' => $data->weixin->getWxID()]); ?>">
                <i class="fa fa-plus fa-fw"></i> 添加菜单</a>
            <span> &nbsp;&nbsp; </span>
            <a class="btn btn-default"
               href="#">
                <i class="fa fa-share fa-fw"></i> 导入公众号菜单</a></a>
        </p>



    </div>
</div>
