<?php
use Admin\Form\LoginForm;

$this->headTitle('登入系统');

// 表单: 帐号
$input = $data->form->get(LoginForm::FIELD_EMAIL);
$input->setAttributes([
    'class'=>'form-control',
    'placeholder'=>'name@example.com',
]);
$this->formLocalMessage($input, [
    \Zend\Validator\NotEmpty::IS_EMPTY => '登录账户不能留空, 请输入您的账号.',
    '__undefined__' => '请使用正确的 E-mail 邮箱地址.',
]);


// 表单: 密码
$input = $data->form->get(LoginForm::FIELD_PASSWORD);
$input->setAttributes([
    'class'=>'form-control',
    'placeholder'=>'在这里输入您的登录密码',
]);
$this->formLocalMessage($input, [
    \Zend\Validator\NotEmpty::IS_EMPTY => '登录密码不能为空, 请输入您的密码.',
    \Zend\Validator\StringLength::TOO_SHORT => '登录密码长度太短了.',
    \Zend\Validator\StringLength::TOO_LONG => '登录密码长度太长了.',
]);

$data->form->get(LoginForm::FIELD_SUBMIT)->setAttributes(['class'=>'btn btn-primary', 'value' => '登入系统']);

$data->form->prepare();

?>

<div id="centered_container" class="centered">
    <div class="login-container">
        <h3 class="text-center">登入管理系统</h3>

        <?php if(0 != $code) { ?>
            <div class="alert alert-warning" role="alert">
                <?php if(\Admin\Service\AuthAdapter::FAILURE_IDENTITY_NOT_FOUND == $code) { ?>
                    <strong>警告!</strong> 登入账户( E-Mail) 地址无效.
                <?php } ?>
                <?php if(\Admin\Service\AuthAdapter::FAILURE_LOCKED == $code) { ?>
                    <strong>警告!</strong> 该账号目前被锁定, 暂不允许登入.
                <?php } ?>
                <?php if(\Admin\Service\AuthAdapter::FAILURE_CREDENTIAL_INVALID == $code) { ?>
                    <strong>警告!</strong> 请使用正确的账号和密码登入.
                <?php } ?>
                <?php if(\Admin\Service\AuthAdapter::FAILURE_EXPIRED == $code) { ?>
                    <strong>警告!</strong> 您的账号已经过期, 禁止登入!
                <?php } ?>
                <?php if(\Admin\Service\AuthAdapter::FAILURE_NOT_ACTIVATED == $code) { ?>
                    <strong>警告!</strong> 您的账号未激活, 禁止登入!
                <?php } ?>
                <?php if(\Admin\Service\AuthAdapter::FAILURE_DISABLED == $code) { ?>
                    <strong>警告!</strong> 您的账号已被禁用, 禁止登入!
                <?php } ?>
            </div>
        <?php } ?>

        <?php echo $this->form()->openTag($data->form); ?>

        <div class="form-group">
            <?php echo $this->formElement($data->form->get(LoginForm::FIELD_CSRF)); ?>
        </div>

        <div class="form-group">
            <?php echo $this->formLabel($data->form->get(LoginForm::FIELD_EMAIL), '登录账户'); ?>
            <?php echo $this->formElement($data->form->get(LoginForm::FIELD_EMAIL)); ?>
            <?php echo $this->formElementErrors($data->form->get(LoginForm::FIELD_EMAIL)); ?>
        </div>

        <div class="form-group">
            <?php echo $this->formLabel($data->form->get(LoginForm::FIELD_PASSWORD), '登录密码'); ?>
            <?php echo $this->formElement($data->form->get(LoginForm::FIELD_PASSWORD)); ?>
            <?php echo $this->formElementErrors($data->form->get(LoginForm::FIELD_PASSWORD)); ?>
        </div>

        <div class="form-group">
            <?php echo $this->formElement($data->form->get(LoginForm::FIELD_SUBMIT)); ?>
        </div>

        <?php echo $this->form()->closeTag(); ?>

    </div>
</div>